### ISSUE TITLE
Add t-shirt sizing for Azure instances

### ISSUE THREAD

**Issue by abhinavg6** [wandb/terraform-google-wandb#129]
We have come up with t-shirt sizes for dedicated instances where each size maps to specific instance types for compute & database, so that we can control our costs, charge customers accordingly, and standardize across the fleet. That configuration is driven from TF. It's already effected for AWS in production so all instances are on a t-shirt size relevant to each customer. But we are yet to make that change for Azure. We need to implement, test and integrate end to end. See the screenshot for the per t-shirt size configuration:

<img width="658" alt="Screenshot 2024-06-04 at 12 23 57 PM" src="https://github.com/wandb/terraform-google-wandb/assets/7208315/662990c5-e665-4fa9-9755-afea721c449a">

**Comment by amanpruthi** [comment]
Linked with wrong project so closing this and created new issue with correct project linked.
