### ISSUE TITLE
Redis Created Despite create_redis Set to False in GCP terraform module

### ISSUE THREAD

**Issue by vijay-wandb** [wandb/terraform-google-wandb#185]

**Comment by vijay-wandb** [comment]
Redis is being created even though `create_redis `is explicitly set to `false` in the deployment using the GCP Terraform module public-dns-with-cloud-dns.

Here’s the variable definition:

```
variable "create_redis" {
  default     = false
  description = "Boolean indicating whether to provision a Redis instance (true) or not (false)."
  nullable    = false
  type        = bool
}
```

The logic in the module at [main.tf#L362](https://github.com/wandb/terraform-google-wandb/blob/main/main.tf#L362C6-L362C46) appears to cause the issue:

`redis = { install = !var.create_redis }`

**Comment by vijay-wandb** [comment]
pr
https://github.com/wandb/terraform-google-wandb/tree/remove-negation-redis

**Comment by danielpanzella** [comment]
The customer should be setting create_redis to true
